PayrollWebApp/Models/PayslipViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Text.Json.Serialization;

namespace PayrollWebApp.Models
{
    public class PayslipViewModel
    {
        public int Id { get; set; }
        public DateTime DateStart { get; set; }
        public string FormattedDateStart => DateStart.ToString("MMM dd, yyyy");
        public DateTime DateEnd { get; set; }
        public string FormattedDateEnd => DateEnd.ToString("MMM dd, yyyy");
        public string? WorkingDaysPattern { get; set; }
        public int ActualWorkingDays { get; set; }
        public float? NetPay { get; set; }
        public string FormattedNetPay => 
            (NetPay ?? 0).ToString("#,###.00");


        // Navigation Property
        [JsonIgnore]
        [BindNever]
        public EmployeeViewModel? Employee { get; set; }
        public int EmployeeId { get; set; } // Foreign Key


        // For Frontend and computation
        public string? EmployeeName { get; set; } = default!;
        public float? DailyRate { get; set; }
        public string FormattedDailyRate =>DailyRate.HasValue ? DailyRate.Value.ToString("#,###0.00") : string.Empty;
        public DateTime? DateOfBirth { get; set; }
        public string FormattedDateOfBirth => DateOfBirth.HasValue ? DateOfBirth.Value.ToString("yyyy-MM-dd") : string.Empty;

    }
}

PayrollWebApp/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using PayrollWebApp.Models;
using PayrollWebApp.Data;
using PayrollWebApp.Services;

namespace PayrollWebApp.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEmployeeApiService _employeeApiService;

        public EmployeesController(IEmployeeApiService apiService)
        {
            _employeeApiService = apiService;
        }


        public async Task<IActionResult> Index()
        {
            var employees = await _employeeApiService.GetAllEmployeeAsync();
            return View(employees);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employee)
        {
            if (!ModelState.IsValid)
                return View(employee);

            var newEmployee = await _employeeApiService.CreateEmployeeAsync(employee);
            if (newEmployee != null)
            {
                TempData["EmployeePageSuccess"] = "Employee successfully Created.";
                return RedirectToAction(nameof(Index));
            }

            TempData["EmployeePageError"] = "Failed to create employee.";
            return View(employee);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var employee = await _employeeApiService.GetEmployeeByIdAsync(id);
            if (employee == null)
                return NotFound();

            return View(employee);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeViewModel employee)
        {
            if (!ModelState.IsValid)
                return View(employee);

            var updateEmployee = await _employeeApiService.UpdateEmployeeAsync(employee);
            if (updateEmployee != null)
            {
                TempData["EmployeePageSuccess"] = "Employee successfully Updated.";
                return RedirectToAction(nameof(Index));
            }

            TempData["EmployeePageError"] = "Failed to update employee.";
            return View(employee);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var isDeleted = await _employeeApiService.DeleteEmployeeAsync(id);
            if (isDeleted)
                TempData["EmployeePageSuccess"] = "Employee successfully Deleted.";
            else
                TempData["EmployeePageError"] = "Failed to delete employee.";

            return RedirectToAction(nameof(Index));
        }
    }
}

PayrollWebApp/Controllers/PayslipsController.cs
using Microsoft.AspNetCore.Mvc;
using PayrollWebApp.Models;
using PayrollWebApp.Services;
using System.Threading.Tasks;

namespace PayrollWebApp.Controllers
{
    public class PayslipsController : Controller
    {

        private readonly IPayslipApiService _payslipApiService;
        private readonly IEmployeeApiService _employeeApiService;

        public PayslipsController(IPayslipApiService payslipApiService, IEmployeeApiService employeeApiService)
        {
            _payslipApiService = payslipApiService;
            _employeeApiService = employeeApiService;
        }

        [Route("Payslips/Employees/{employeeId}")]
        public async Task<IActionResult> Index(int employeeId)
        {
            var employeePayslips = await _payslipApiService.GetAllPayslipByEmployeeIdAsync(employeeId);
            ViewBag.EmployeeId = employeeId;
            return View(employeePayslips);
        }

        [HttpGet]
        [Route("Payslips/Employees/{employeeId}/Create")]
        public async Task<IActionResult> Create(int employeeId)
        {
            var employee = await _employeeApiService.GetEmployeeByIdAsync(employeeId);
            var payslip = new PayslipViewModel
            {
                EmployeeId = employeeId,
                DateStart = DateTime.Today,
                DateEnd = DateTime.Today,
                EmployeeName = $"{employee.FirstName} {employee.LastName}",
                DailyRate = employee.DailyRate,
                DateOfBirth = employee.DoB
            };

            ViewBag.EmployeeId = employeeId;
            return View(payslip);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Payslips/Employees/{employeeId}/Create")]
        public async Task<IActionResult> Create(PayslipViewModel payslip)
        {
            if (ModelState.IsValid)
            {
                var newPayslip = await _payslipApiService.CreatePayslipAsync(payslip);
                if (newPayslip != null)
                {
                    TempData["PayslipPageSuccess"] = "Payslip successfully Created.";
                    return RedirectToAction(nameof(Index), new { employeeId = payslip.EmployeeId });
                }
            }

            TempData["PayslipPageError"] = "Failed to create payslip.";
            return View(payslip);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            PayslipViewModel payslip = await _payslipApiService.GetPayslipByIdAsync(id);
            if (payslip == null)
                return NotFound();

            var employee = await _employeeApiService.GetEmployeeByIdAsync(payslip.EmployeeId);
            payslip.EmployeeName = $"{employee.FirstName} {employee.LastName}";
            payslip.DailyRate = employee.DailyRate;
            payslip.EmployeeId = employee.Id;
            payslip.DateOfBirth = employee.DoB;

            return View(payslip);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PayslipViewModel payslip)
        {
            if (!ModelState.IsValid)
                return View(payslip);

            var updatedPayslip = await _payslipApiService.EditPayslipAsync(payslip);
            if (updatedPayslip != null)
            {
                TempData["PayslipPageSuccess"] = "Payslip successfully Updated.";
                return RedirectToAction(nameof(Index), new { employeeId = payslip.EmployeeId });
            }

            TempData["PayslipPageError"] = "Failed to update payslip.";
            return View(payslip);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, int employeeId)
        {
            bool result = await _payslipApiService.DeletePayslipAsync(id);
            if (result)
                TempData["PayslipPageSuccess"] = "Payslip successfully deleted.";
            else
                TempData["PayslipPageError"] = "Failed to delete payslip.";

            return RedirectToAction(nameof(Index), new { employeeId = employeeId });
        }
    }
}

PayrollWebApp/Views/Payslips/Create.cshtml
@using PayrollWebApp.Models;
@using PayrollWebApp.Data;
@model PayslipViewModel;

@{
    ViewData["Title"] = "Create Payslip";
}

<h2 style="padding-bottom: 25px">Create Payslip</h2>

<form asp-action="Create" asp-route-employeeId="@Model.EmployeeId" method="post">

    <div class="mb-3">
        <input asp-for="EmployeeId" type="hidden" />
        <input type="hidden" id="DateOfBirth" value="@Model.FormattedDateOfBirth" />
    </div>

    <div class="mb-3">
    <label asp-for="EmployeeName" class="form-label">Employee Name</label>
    <input asp-for="EmployeeName" type="text" class="form-control" disabled />
    <span asp-validation-for="EmployeeName" class="text-danger"></span>
    </div>

    <div class="mb-3">
    <label asp-for="FormattedDailyRate" class="form-label">Daily Rate</label>
        <input asp-for="FormattedDailyRate" type="text" class="form-control" disabled />
    <span asp-validation-for="FormattedDailyRate" class="text-danger"></span>
    </div>

    <div class="mb-3">
    <label asp-for="DateStart" class="form-label">Start Period</label>
    <input asp-for="DateStart" type="date" class="form-control" />
    <span asp-validation-for="DateStart" class="text-danger"></span>
    </div>

    <div class="mb-3">
    <label asp-for="DateEnd" class="form-label">Start Period</label>
    <input asp-for="DateEnd" type="date" class="form-control" />
    <span asp-validation-for="DateEnd" class="text-danger"></span>
    </div>

    <div class="mb-3">
    <label class="form-label">Select Working Days</label>

    <div class="form-check">
    <input asp-for="WorkingDaysPattern" class="form-check-input" type="radio" value="MWF" id="pattern-mwf" checked/>
    <label class="form-check-label" for="pattern-mwf">Mon, Wed, Fri</label>
    </div>
    <div class="form-check">
    <input asp-for="WorkingDaysPattern" class="form-check-input" type="radio" value="TTHS" id="pattern-tths" />
    <label class="form-check-label" for="pattern-tths">Tue, Thu, Sat</label>
    </div>
    </div>

    <div class="mb-3">
    <label asp-for="ActualWorkingDays" class="form-label">Number of Working Days</label>
        <input asp-for="ActualWorkingDays" type="text" class="form-control" readonly />
    <span asp-validation-for="ActualWorkingDays" class="text-danger"></span>
    </div>

    <div class="mb-3">
    <label asp-for="NetPay" class="form-label">Take Home Pay</label>
        <input asp-for="NetPay" type="text" class="form-control" readonly />
    <span asp-validation-for="NetPay" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
    <a asp-action="Index" asp-route-employeeId="@Model.EmployeeId" class="btn btn-secondary">Cancel</a>
</form>

<script>
const EMPLOYEE_API_URL = "@Const.API_BASE/@Const.EMPLOYEES_ENDPOINT";
</script>

<script src="~/js/site.js"></script>

PayrollWebApp/Views/Payslips/Edit.cshtml
@using PayrollWebApp.Models;
@using PayrollWebApp.Data;
@model PayslipViewModel;

@{
    ViewData["Title"] = "Edit Payslip";
}

<h2 style="padding-bottom: 25px">Edit Payslip</h2>

<form asp-action="Edit" asp-route-employeeId="@Model.EmployeeId" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="EmployeeId" />

    <div class="mb-3">
        <input asp-for="EmployeeId" type="hidden" />
        <input type="hidden" id="DateOfBirth" value="@Model.FormattedDateOfBirth" />
    </div>

    <div class="mb-3">
        <label asp-for="EmployeeName" class="form-label">Employee Name</label>
        <input asp-for="EmployeeName" type="text" class="form-control" disabled />
        <span asp-validation-for="EmployeeName" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="FormattedDailyRate" class="form-label">Daily Rate</label>
        <input asp-for="FormattedDailyRate" type="text" class="form-control" disabled />
        <span asp-validation-for="FormattedDailyRate" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="DateStart" class="form-label">Start Period</label>
        <input asp-for="DateStart" type="date" class="form-control" />
        <span asp-validation-for="DateStart" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="DateEnd" class="form-label">Start Period</label>
        <input asp-for="DateEnd" type="date" class="form-control" />
        <span asp-validation-for="DateEnd" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label class="form-label">Select Working Days</label>

        <div class="form-check">
            <input asp-for="WorkingDaysPattern" class="form-check-input" type="radio" value="MWF" id="pattern-mwf" checked />
            <label class="form-check-label" for="pattern-mwf">Mon, Wed, Fri</label>
        </div>
        <div class="form-check">
            <input asp-for="WorkingDaysPattern" class="form-check-input" type="radio" value="TTHS" id="pattern-tths" />
            <label class="form-check-label" for="pattern-tths">Tue, Thu, Sat</label>
        </div>
    </div>

    <div class="mb-3">
        <label asp-for="ActualWorkingDays" class="form-label">Number of Working Days</label>
        <input asp-for="ActualWorkingDays" type="text" class="form-control" readonly />
        <span asp-validation-for="ActualWorkingDays" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="NetPay" class="form-label">Take Home Pay</label>
        <input asp-for="NetPay" type="text" class="form-control" readonly />
        <span asp-validation-for="NetPay" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>
    <a asp-action="Index" asp-route-employeeId="@Model.EmployeeId" class="btn btn-secondary">Cancel</a>
</form>

<script>
    const EMPLOYEE_API_URL = "@Const.API_BASE/@Const.EMPLOYEES_ENDPOINT";
</script>

<script src="~/js/site.js"></script>

PayrollWebApp/Views/Payslips/Index.cshtml
@using PayrollWebApp.Models;
@using PayrollWebApp.Data;
@model IEnumerable<PayslipViewModel>;

@{
    ViewData["Title"] = "Payslip";
}

@if (TempData["PayslipPageSuccess"] != null)
{
    <div class="alert alert-success">
        @TempData["PayslipPageSuccess"]
    </div>
}

@if (TempData["PayslipPageError"] != null)
{
    <div class="alert alert-danger">
        @TempData["PayslipPageError"]
    </div>
}

<h2>Employee Payslips</h2>

<div style="padding-bottom: 30px">
    <a asp-action="Index" asp-controller="Employees" class="btn btn-secondary">Back <i class="bi bi-arrow-90deg-left"></i></a>
    <a asp-action="Create" asp-route-employeeId="@ViewBag.EmployeeId" class="btn btn-primary">
        Create Payslip <i class="bi bi-currency-dollar"></i>
    </a>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Start Period</th>
            <th>End Period</th>
            <th>Working Days</th>
            <th>Net</th>
            <th style="text-align: center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var payslip in Model)
        {
            <tr>
                <td>@payslip.FormattedDateStart</td>
                <td>@payslip.FormattedDateEnd</td>
                <td>@payslip.WorkingDaysPattern</td>
                <td>@payslip.FormattedNetPay</td>
                <td style="text-align: center">
                    <a asp-action="Edit" asp-route-id="@payslip.Id" class="btn btn-primary edit-button">Edit</a>
                    <form asp-action="Delete" asp-route-id="@payslip.Id" method="post" style="display:inline;">
                        <input type="hidden" name="id" value="@payslip.Id" />
                        <input type="hidden" name="employeeId" value="@ViewBag.EmployeeId" />
                        <button type="submit" class="btn btn-danger" 
                                onclick="return confirm('Are you sure you want to delete this payslip?');">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    const EMPLOYEE_API_URL = "@Const.API_BASE/@Const.EMPLOYEES_ENDPOINT";
    document.addEventListener('DOMContentLoaded', getEmployeeById);
</script>

<script src="~/js/site.js"></script>